backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images/small"
collections:
  - name: "landing"
    label: "Landing pages"
    files:
      - label: "Home"
        name: _index
        file: "site/content/_index.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - label: "Menu"
            name: "menu"
            widget: "select"
            options: ["none", "main"]
          - label: "Weight"
            name: "weight"
            widget: "number"
            valueType: "int"
            min: 0
            max: 100
          - name: book
            label: "Book"
            widget: object
            fields:
              - label: Image
                name: image
                widget: image
              - label: "Image alt text"
                name: alt
                widget: string
              - label: "Buy URL"
                name: buy
                widget: string
              - label: Praise
                name: praise
                widget: list
                fields:
                  - label: Quote
                    name: quote
                    widget: markdown
                  - label: Attribution
                    name: attribution
                    widget: string
                  - label: Link
                    name: link
                    widget: string
          - label: "Bio"
            name: bio
            widget: object
            fields:
              - label: "Title"
                name: title
                widget: string
              - label: Image
                name: image
                widget: image
              - label: Text
                name: text
                widget: markdown


  - name: "pages"
    label: "Pages"
    folder: "site/content"
    create: true
    slug: "{{slug}}"
    filter: {field: "layout", value: "page"}
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - label: "Menu"
        name: "menu"
        widget: "select"
        options: ["none", "main"]
      - label: "Weight"
        name: "weight"
        widget: "number"
        valueType: "int"
        min: 0
        max: 100