backend:
  name: git-gateway
  branch: design-2
media_folder: "static/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "content"
    create: true
    path: "{{section}}/{{slug}}"
    media_folder: ""
    public_folder: ""
    filter: { field: "layout", value: "page" }
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "page" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: Hero image
        name: image
        widget: object
        required: false
        fields:
          - { label: "Image", name: "src", widget: "image", required: false }
          - {
              label: "Image alt text",
              name: "alt",
              widget: "string",
              required: false,
            }
          - {
              label: "Style",
              name: "style",
              widget: "hidden",
              default: "cover",
            }
      - {
          label: "Section",
          name: "section",
          widget: "string",
          required: false,
          pattern:
            [
              '[0-9a-z\/]+',
              "Should only contain lowercase letters, numerals or the forward slash (/) character",
            ],
        }
      - {
          label: "URL segment",
          name: "slug",
          widget: "string",
          pattern:
            [
              '[0-9a-z\/]+',
              "Should only contain lowercase letters, numerals or the forward slash (/) character",
            ],
        }
      - label: Menu
        name: menu_section
        widget: object
        collapsed: true
        fields:
          - label: "Menu"
            name: "menu"
            widget: "select"
            options: ["main"]
            multiple: true
            required: false
          - label: "Weight"
            name: "weight"
            widget: "number"
            valueType: "int"
            min: 0
            max: 100
            required: false
